[package]
name = "application"
version = "0.1.0"
edition = "2018"

[dependencies]
futures-util = "0.3.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.12.0", features = ["full"] }
tokio-tungstenite = "0.15.0"
rand = "0.8.4"

[profile.release]
panic = "abort"
codegen-units = 1
opt-level = "z"
lto = true
